2021-07-15 11:28:35,069 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:30:40,591 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:30:42,894 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:30:45,619 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:49:44,922 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:49:46,609 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:54:51,639 - [INFO] - __main__ - (main.py).main(7) - Программа стартует
2021-07-15 11:54:51,640 - [INFO] - package1 - (package1.py).process(6) - Перед процессом
2021-07-15 11:54:51,640 - [INFO] - package1 - (package1.py).process(8) - После процесса
2021-07-15 11:54:51,640 - [WARNING] - __main__ - (main.py).main(9) - Это должно появиться как в консоли, так и в файле журнала
2021-07-15 11:54:51,640 - [INFO] - __main__ - (main.py).main(10) - Программа завершила работу
2021-07-15 11:54:51,640 - [ERROR] - __main__ - (main.py).main(14) - division by zero
Traceback (most recent call last):
  File "/home/backhub/PycharmProjects/graylog_test/main.py", line 12, in main
    1/0
ZeroDivisionError: division by zero
